settings:
  title: '状态页面'  # 标题
  url: 'https://status-page.eidam.dev'  # 用于Slack消息的URL
  logo: logo-192x192.png  # 位于./public/文件夹中的图片
  daysInHistogram: 90  # 直方图中显示的天数
  collectResponseTimes: true  # 是否收集CRON位置的平均响应时间

  allmonitorsOperational: '所有系统运行正常'  # 所有监控正常时的状态消息
  notAllmonitorsOperational: '部分系统运行异常'  # 有监控不正常时的状态消息
  monitorLabelOperational: '运行正常'  # 单个监控正常时的标签
  monitorLabelNotOperational: '运行异常'  # 单个监控不正常时的标签
  monitorLabelNoData: '无数据'  # 单个监控没有数据时的标签
  dayInHistogramNoData: '无数据'  # 直方图中无数据的天数标签
  dayInHistogramOperational: '一切正常'  # 直方图中正常的天数标签
  dayInHistogramNotOperational: ' 次事件'  # 直方图中不正常的天数标签，格式为 xx 次事件

monitors:
  - id: zh52.cn  # 唯一标识符
    name: zh52.cn  # 名称
    description: 'zh52.cn 主站'  # 描述，默认=空
    url: 'https://zh52.cn/'  # 需要获取的URL
    method: GET  # 请求方法，默认=GET
    expectStatus: 200  # 正常状态码，默认=200
    followRedirect: false  # 是否跟随重定向，默认=false
    linkable: true  # 标题是否可链接，默认=true

  - id: www-zh52-cn
    name: www.zh52.cn
    description: 'www.zh52.cn'
    url: 'https://www.zh52.cn'
    method: GET
    expectStatus: 200
    linkable: true

  - id: blog-zh52-cn
    name: blog.zh52.cn
    description: 'zh52.cn'
    url: 'https://blog.zh52.cn/'
    method: GET
    expectStatus: 200
    linkable: true

  - id: mz-zh52-cn
    name: mz.zh52.cn
    description: 'mz.zh52.cn'
    url: 'https://mz.zh52.cn/'
    method: GET
    expectStatus: 200
    linkable: true

  - id: m-zh52-cn
    name: m.zh52.cn
    description: 'm.zh52.cn'
    url: 'https://m.zh52.cn/'
    method: GET
    expectStatus: 200
    linkable: true

  - id: m-anchen-us-kg
    name: m.anchen.us.kg
    description: 'm.anchen.us.kg、'
    url: 'https://m.anchen.us.kg/'
    method: GET
    expectStatus: 200
    linkable: true
    
  - id: alist.web66.us.kg
    name: alist.web66.us.kg
    description: 'alist.web66.us.kg、'
    url: 'https://alist.web66.us.kg/'
    method: GET
    expectStatus: 200
    linkable: true
